
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: iot-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: dockercompose-analytics-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_DB
          value: analyticsdb
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: pass
        - name: POSTGRES_HOST
          value: postgres-analytics
        - name: POSTGRES_PORT
          value: "5432"
        - name: RABBITMQ_HOST
          value: rabbitmq
