
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-iot
  namespace: iot-demo
spec:
  serviceName: postgres-iot
  replicas: 1
  selector:
    matchLabels:
      app: postgres-iot
  template:
    metadata:
      labels:
        app: postgres-iot
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: iotdb
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: pass
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
